# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.11:latest

tasks:
  - name: Initial setup
    init: |
      # Commands to run only on the first start
      if [ ! -d "pipeline" ]; then
        echo "Running first-time setup commands"

        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        ~/miniconda3/bin/conda init bash
        exec bash
        conda create --name kedro-environment python=3.11 -y
        conda activate kedro-environment
        pip install --upgrade pip
        pip install kedro
        kedro new --starter=spaceflights-pandas-viz --name=pipeline
        cd pipeline/
        pip install -r requirements.txt
        cd notebooks/
        curl -s https://api.github.com/repos/AdamPrzychodniPrivate/notebook-templates/contents/ | jq -r '.[] | .download_url' | xargs -n 1 -I {} curl -O {}
        cd ..
        conda deactivate

      fi
    command: |
      # Commands to run every time the workspace starts
      echo "Running regular startup commands"
      # Put your regular startup commands here

      sudo apt-get update
      sudo apt-get install tree
      conda create --name kedro-environment python=3.11 -y
      conda activate kedro-environment
      pip install --upgrade pip
      pip install kedro
      cd pipeline/
      pip install -r requirements.txt

ports:
 - port: 8888  # Default Jupyter Notebook port
