# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.11:latest

tasks:
  - name: Initial setup
    init: |
      # Check if this is the first run by looking for the 'pipeline' directory
      if [ ! -d "pipeline" ]; then
        echo "Running first-time setup commands"

        # Downloading and installing Miniconda
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3

        # Initializing Conda and sourcing the bashrc to refresh the shell environment
        ~/miniconda3/bin/conda init bash
        source ~/.bashrc

        # Creating a new Conda environment with Python 3.10
        conda create --name kedro-environment python=3.10 -y
        conda activate kedro-environment

        # Installing Python packages needed for the project
        pip install --upgrade pip
        pip install kedro

        # Setting up the Kedro project
        kedro new --starter=spaceflights-pandas-viz --name=pipeline
        cd pipeline/
        pip install -r requirements.txt

        # Downloading notebook templates from GitHub
        cd notebooks/
        curl -s https://api.github.com/repos/AdamPrzychodniPrivate/notebook-templates/contents/ | jq -r '.[] | .download_url' | xargs -n 1 -I {} curl -O {}
        cd ..

        # Deactivating the Conda environment
        conda deactivate
      fi

    command: |
      # Regular startup commands for every subsequent run
      echo "Running regular startup commands"

      # Updating system packages
      sudo apt-get update
      sudo apt-get install tree

      # Reinitializing the Conda environment and installing dependencies
      conda create --name kedro-environment python=3.10 -y
      conda activate kedro-environment
      pip install --upgrade pip
      pip install kedro
      cd pipeline/
      pip install -r requirements.txt

ports:
 - port: 8888  # Default Jupyter Notebook port
